In [81]:
(import [numpy :as np])
(require [helpers [*]])

[None, None]

In [82]:
(setv a (np.array [0 1 2 3]))

[None]

In [83]:
a

[array([0, 1, 2, 3])]

In [84]:
;; NumPy arrays are memory efficient and optimized for numerical computations

[]

In [85]:
(cut [(import [time [time]])
(setv L (range 1000))
(setv time1 (time))
(lfor i L (** i 2))
(setv time2 (time))
(- time2 time1)] 3 6)

[[[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26244, 26

In [86]:
(cut [(import [time [time]])
(setv a (np.arange 1000))
(setv time1 (time))
(** a 2)
(setv time2 (time))
(- time2 time1)] 3 6)

[[array([     0,      1,      4,      9,     16,     25,     36,     49,
           64,     81,    100,    121,    144,    169,    196,    225,
          256,    289,    324,    361,    400,    441,    484,    529,
          576,    625,    676,    729,    784,    841,    900,    961,
         1024,   1089,   1156,   1225,   1296,   1369,   1444,   1521,
         1600,   1681,   1764,   1849,   1936,   2025,   2116,   2209,
         2304,   2401,   2500,   2601,   2704,   2809,   2916,   3025,
         3136,   3249,   3364,   3481,   3600,   3721,   3844,   3969,
         4096,   4225,   4356,   4489,   4624,   4761,   4900,   5041,
         5184,   5329,   5476,   5625,   5776,   5929,   6084,   6241,
         6400,   6561,   6724,   6889,   7056,   7225,   7396,   7569,
         7744,   7921,   8100,   8281,   8464,   8649,   8836,   9025,
         9216,   9409,   9604,   9801,  10000,  10201,  10404,  10609,
        10816,  11025,  11236,  11449,  11664,  11881,  12100,  12321,
    

In [87]:
(get a (slice 1 10 2))

[array([1, 3, 5, 7, 9])]

In [88]:
(get a (slice #*[1 10 2]))

[array([1, 3, 5, 7, 9])]

In [89]:
(get a 1)

[1]

In [90]:
(setv a (np.array [[0 1 2 3 4 5]
     [10 11 12 13 14 15]
     [20 21 22 23 24 25]
     [30 31 32 33 34 35]
     [40 41 42 43 44 45]
     [50 51 52 53 54 55]]))


[None]

In [91]:
a

[array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])]

In [92]:
(get a 2)

[array([20, 21, 22, 23, 24, 25])]

In [93]:
(get a 2 3)

[23]

In [94]:
(get a [[0 1 2 3 4] [1 2 3 4 5]])

[array([ 1, 12, 23, 34, 45])]

In [95]:
(get a [(slice 3) [0 2 5]])

[array([[ 0,  2,  5],
       [10, 12, 15],
       [20, 22, 25]])]

In [96]:
(get a [(slice 3 6) [0 2 5]])

[array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])]

In [97]:
(nget a 3: (, 1 2 3 4))

[array([[31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54]])]

In [98]:
#s(a 3: (, 1 2 3 4))

[array([[31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54]])]

In [99]:
#s(a 3:6 [0 2 5])

[array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])]

In [100]:
#s(a [0 2 5] ::2)

[array([[ 0,  2,  4],
       [20, 22, 24],
       [50, 52, 54]])]

In [101]:
#s(a 1:5:2 :4:3)

[array([[10, 13],
       [30, 33]])]

In [102]:
;;;;;;;;;;;;;;;;;;
;; Okay, now that I'm familiar with Hy (a bit), let's actually start on the
;; SciPy Lectures
;;;;;;;;;;;;;;;;;;

[]

In [103]:
(import [numpy :as np])
(setv a (np.array [0 1 2 3]))
a

[None, None, array([0, 1, 2, 3])]

In [104]:
(import [time [time]])

[None]

In [105]:
(do (setv L (range 100000))
    (setv time0 (time))
    (lfor i L (** i 2))
    (setv time1 (time))
    (- time1 time0))

[0.037229061126708984]

In [106]:
(do (setv A (np.arange 100000))
    (setv time0 (time))
    (** A 2)
    (setv time1 (time))
    (- time1 time0))

[0.0008382797241210938]

In [107]:
(help np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

[None]

In [108]:
(np.lookfor "create array")

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.asarray
    Convert the input to an array.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.recarray
    Construct an ndarray that allows field access using attributes.
numpy.chararray
    chararray(shape, itemsize=1, unicode=Fa

[None]

In [109]:
(. np cron * ?) ;; I haven't found a way to do the np.cron*? equivalent

Traceback (most recent call last):
  File "/home/josiah/miniconda3/envs/scipy-lectures/lib/python3.7/site-packages/calysto_hy/kernel.py", line 137, in do_execute_direct
    eval(code, self.env)
  File "In [109]", line 1, in <module>
AttributeError: module 'numpy' has no attribute 'cron'



In [110]:
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 1.3.1.2 Creating Arrays
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[]

In [111]:
;; 1-D
(setv a (np.array [0 1 2 3]))
a
a.ndim
a.shape
(len a)

[None, array([0, 1, 2, 3]), 1, (4,), 4]

In [112]:
;; 2-D, 3-D, ...:
(setv b (np.array [[0 1 2] [3 4 5]]))
b
b.ndim
b.shape
(len b)

[None, array([[0, 1, 2],
       [3, 4, 5]]), 2, (2, 3), 2]

In [113]:
(setv c (np.array [[[1] [2]] [[3] [4]]]))
c
c.ndim
c.shape
(len c)

[None, array([[[1],
        [2]],

       [[3],
        [4]]]), 3, (2, 2, 1), 2]

In [114]:
;; Functions for creating arrays
; - Evenly spaced:
(setv a (np.arange 10)) ; 0 .. n - 1 (!)
a
(setv b (np.arange 1 9 2)) ; start, end (exclusive), step
b

[None, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), None, array([1, 3, 5, 7])]

In [115]:
; - By number of points (still evenly spaced):
(setv c (np.linspace 0 1 6)) ; start, end, num-points
c
(setv d (np.linspace 0 1 5 :endpoint False))
d

[None, array([0. , 0.2, 0.4, 0.6, 0.8, 1. ]), None, array([0. , 0.2, 0.4, 0.6, 0.8])]

In [116]:
; - Common arrays:
(setv a (np.ones '(3 3)))
a
(setv b (np.zeros '(2 2 2)))
b
(setv c (np.eye 3))
c
(setv d (np.diag (np.array [1 2 3 4])))
d

[None, array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]]), None, array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]]), None, array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), None, array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])]

In [117]:
; - np.random: random numbers (Mersenne Twister PRNG)
(setv a (np.random.rand 4))       ; uniform in [0 1]
a
(setv b ((. np random randn) 4))  ; Gaussian
b
((. np random seed) 1234)         ; Setting the random seed
(setv c (np.random.randn 4))
c

[None, array([0.92974146, 0.15774431, 0.17934442, 0.5272375 ]), None, array([ 0.48051187, -0.82987114, -0.05201442, -0.84561438]), None, None, array([ 0.327431  , -2.0992355 ,  0.32043975,  0.12437438])]

In [118]:
(help np.empty)

Help on built-in function empty in module numpy.core.multiarray:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Ret

[None]

In [119]:
(np.empty [3 2 4])

[array([[[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 6.89976514e-310,
         1.11164770e-321]],

       [[6.89979932e-310, 6.89979932e-310, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[4.65532116e-310, 6.89979652e-310, 6.89979750e-310,
         6.89979652e-310],
        [6.89978871e-310, 6.89976551e-310, 4.65532117e-310,
         4.65532116e-310]]])]

In [120]:
(np.eye 5) ; It's obvious this creates the identity matrix for the specified dimension

[array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])]

In [121]:
(np.eye 5 2)

[array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])]

In [122]:
(np.eye 5 3 1)

[array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])]

In [123]:
(np.eye 5 3 2)

[array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])]

In [124]:
(np.eye 5 3 0)

[array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])]

In [125]:
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 1.3.1.3 Basic data types
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[]

In [126]:
(setv a (np.array [1 2 3]))
a.dtype
(setv b (np.array [1. 2. 3.]))
b.dtype

[None, dtype('int64'), None, dtype('float64')]

In [127]:
; Explicitly setting the dtype
(setv c (np.array [1 2 3] :dtype float))
c.dtype

[None, dtype('float64')]

In [128]:
; The default dtype is floating point
(setv a (np.ones [3 3]))
a.dtype

[None, dtype('float64')]

In [129]:
(+ 2 (* 3 1j))

[(2+3j)]

In [130]:
;; Other types
; complex
(setv d (np.array [(+ 1 2j) (+ 3 4j) (+ 5 (* 6 1j))]))
d
d.dtype

[None, array([1.+2.j, 3.+4.j, 5.+6.j]), dtype('complex128')]

In [131]:
; bool
(setv e (np.array [True False False True]))
e
e.dtype

[None, array([ True, False, False,  True]), dtype('bool')]

In [132]:
; strings
(setv f (np.array ["Bonjour" "Hello" "Dia is Muera duit"]))
f
f.dtype

[None, array(['Bonjour', 'Hello', 'Dia is Muera duit'], dtype='<U17'), dtype('<U17')]

In [133]:
; and there's also others, like int32, int64, uint32, uint64, and probably more

[]

In [134]:
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 1.3.1.4 Basic visualization
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[]

In [137]:
(import [matplotlib.pyplot :as plt])

[None]

In [211]:
%matplotlib "Qt5Cairo"

In [212]:
; 1D plotting

[]

In [213]:
(setv x (np.linspace 0 3 20))
(setv y (np.linspace 0 9 20))
(plt.plot x y) ; line plot

[None, None, [<matplotlib.lines.Line2D object at 0x7f035c421c50>]]

In [214]:
(plt.show) ;; Calysto_Hy doesn't yet support inline. See: https://github.com/Calysto/calysto_hy/issues/6

[None]

In [215]:
(plt.plot x y "o") ; dot plot

[[<matplotlib.lines.Line2D object at 0x7f035b48c390>]]

In [216]:
(plt.show) ;; Will show separate window when executed

[None]

In [217]:
; 2D arrays (such as images):

[]

In [218]:
(setv image (np.random.rand 30 30))

[None]

In [219]:
(plt.imshow image :cmap plt.cm.hot)

In [220]:
(plt.colorbar)

In [221]:
(plt.show)

[None]

In [222]:
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 1.3.1.5 Indexing and Slicing
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[]

In [226]:
;; The items of a array can be accessed and assigned teh same way as other Python sequences
(setv a (np.arange 10))
a
(, #s(a 0) #s(a 2) #s(a -1))

[None, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (0, 2, 9)]

In [227]:
;; The usual Python idiom for reversing a sequence is supported
#s(a ::-1)

[array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])]

In [228]:
;; For multidimensional arrays, indexes are tuples of integers
(setv a (np.diag (np.arange 3)))
a
#s(a 1 1)

[None, array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]]), 1]

In [231]:
(setv #s(a 2 1) 10)
a

[None, array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])]

In [232]:
#s(a 1)

[array([0, 1, 0])]

In [233]:
;; NOTE:
; - In 2D, the first dimension corresponds to rows, and the second to columns
; - For multidimensional a, #s(a 0) is interpreted by taking all elements in the unspecified
;   dimensions.

[]

In [235]:
;; Slicing: Arrays, like other Python sequences can also be sliced.
(setv a (np.arange 10))
a
#s(a 2:9:3) ;; start:end:step

[None, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 5, 8])]

In [236]:
; Note that the last index is excluded!
#s(a :4)

[array([0, 1, 2, 3])]

In [237]:
; All three slice components are not required: by default, start is 0, end is len + 1, and
; step is 1
#s(a 1:3)
#s(a ::2)
#s(a 3:)

[array([1, 2]), array([0, 2, 4, 6, 8]), array([3, 4, 5, 6, 7, 8, 9])]

In [238]:
; You can also combine assignment and slicing
(setv a (np.arange 10))
a

[None, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [239]:
(setv #s(a 5:) 10)
a

[None, array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])]

In [240]:
(setv b (np.arange 5))
b
(setv #s(a 5:) #s(b ::-1))
a

[None, array([0, 1, 2, 3, 4]), None, array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])]