In [2]:
import numpy as np

In [7]:
# Scalar ops
a = np.array([1,2,3,4])
a_plus = a + 1 # scalar addition
a_prod = 2*a # scalar multiplication
a_exp = a**2 # scalar exponentiation

print(a_plus)
print(a_prod)
print(a_exp)

[2 3 4 5]
[2 4 6 8]
[ 1  4  9 16]


In [21]:
# All arithetic operates element-wise

# Scalar addition (again)
b = np.ones(4) + 1
print("B = " + str(b))

# Vector addition/subtraction
a_minus_b = a - b
print("A - B = " + str(a_minus_b))

# Vector multiplication
a_prod_b = a * b
print("A * B = " + str(a_prod_b))

# Combining multiple operations in a single statement
j = np.arange(5)
print(2**(j + 1) - j)

B = [ 2.  2.  2.  2.]
A - B = [-1.  0.  1.  2.]
A * B = [ 2.  4.  6.  8.]
[ 2  3  6 13 28]


In [22]:
# Pure Python vs NumPy performance characteristics

a = np.arange(10000)
%timeit a + 1

The slowest run took 9.71 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.68 µs per loop


In [25]:
l = range(10000)
%timeit [i + 1 for i in l]

1000 loops, best of 3: 684 µs per loop


In [26]:
# NumPy is much faster

In [28]:
# Matrix multiplication

# ! This is NOT matrix multiplication, it is array multiplication
c = np.ones((3,3))
print("C = \n" + str(c))
c_array_squared = c * c
print("C * C = \n" + str(c_array_squared))

# This IS matrix multiplication (dot product)
c_matrix_squared = c.dot(c)
print("C dot C = \n" + str(c_matrix_squared))

C = 
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
C * C = 
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
C dot C = 
[[ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]]


In [75]:
# Exercises

# Add even elements with odd elements
x = np.arange(20)
even = x[np.arange(0,20,2)]
odd = x[np.arange(1,20,2)]
print("Even = " + str(even))
print("Odd = " + str(odd))
print("Even + Odd (element-wise) = " + str(even + odd))
%timeit x = np.arange(20); x[np.arange(0,20,2)] + x[np.arange(1,20,2)]
def is_even(n): return n % 2 == 0
def is_odd(n): return not is_even(n)
y = range(20)
even_y = filter(is_even, y)
odd_y = filter(is_odd, y)
print("Even + Odd = " + str([a[0] + a[1] for a in zip(even_y, odd_y)]))
%timeit y = range(20); [a[0] + a[1] for a in zip(filter(is_even, y), filter(is_odd, y))]

Even = [ 0  2  4  6  8 10 12 14 16 18]
Odd = [ 1  3  5  7  9 11 13 15 17 19]
Even + Odd (element-wise) = [ 1  5  9 13 17 21 25 29 33 37]
The slowest run took 11.50 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.67 µs per loop
Even + Odd = [1, 5, 9, 13, 17, 21, 25, 29, 33, 37]
100000 loops, best of 3: 12.2 µs per loop
