In [1]:
import numpy as np

In [2]:
# 1.
# Form the following 2D array using NumPy fxns.
# [[1,  6, 11],
#  [2,  7, 12],
#  [3,  8, 13],
#  [4,  9, 14],
#  [5, 10, 15]]

mat = np.arange(1,16).reshape((3,5)).T
mat

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [3]:
# Also, create a second array which contains only the 2nd and 4th rows.
new_mat = mat[[1,3]]
new_mat

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [4]:
# 2.
# Divide each column of the array np.arange(25).reshape(5,5) elementwise with the array [1., 5, 15, 20]
mat = np.arange(25).reshape(5,5)
arr = np.array([1., 5, 10, 15, 20])
mat / arr[:, np.newaxis]
# New access turns the arr which is a row into a column - autobroadcasting handles propogating the row across all the
# columns of mat.

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.2       ,  1.4       ,  1.6       ,  1.8       ],
       [ 1.        ,  1.1       ,  1.2       ,  1.3       ,  1.4       ],
       [ 1.        ,  1.06666667,  1.13333333,  1.2       ,  1.26666667],
       [ 1.        ,  1.05      ,  1.1       ,  1.15      ,  1.2       ]])

In [5]:
# 3.
# Generate a 10 x 3 matrix of random numbers in the Set [0,1].  For each row, choose the number closest to 0.5.
#   Additional instructions: use `abs` and `argsort` to pick the column j of the closest number to 0.5 for each row
#                            Use fancy indexing to extract the numbers

In [6]:
mat = np.random.sample((10,3))
print(mat)
distances_from_half = np.abs(mat - 0.5)
print(distances_from_half)
sort_values = np.argsort(distances_from_half)
print(sort_values)
closest_indices = sort_values
closest_index_pairs = [ (i, sort_values[i, 0]) for i in np.arange(0, sort_values.shape[0]) ]
closest_numbers = [ mat[i[0], i[1]] for i in closest_index_pairs ]
closest_numbers

[[ 0.08793435  0.73177254  0.62805837]
 [ 0.36123025  0.64536873  0.18273487]
 [ 0.50178721  0.91285468  0.96157728]
 [ 0.57241649  0.73591995  0.20317841]
 [ 0.96975435  0.286237    0.28669129]
 [ 0.84426798  0.49316912  0.6413791 ]
 [ 0.59575333  0.06320073  0.69599347]
 [ 0.35664221  0.05240474  0.93805705]
 [ 0.63341822  0.05127082  0.31970119]
 [ 0.09830292  0.06227591  0.25454979]]
[[ 0.41206565  0.23177254  0.12805837]
 [ 0.13876975  0.14536873  0.31726513]
 [ 0.00178721  0.41285468  0.46157728]
 [ 0.07241649  0.23591995  0.29682159]
 [ 0.46975435  0.213763    0.21330871]
 [ 0.34426798  0.00683088  0.1413791 ]
 [ 0.09575333  0.43679927  0.19599347]
 [ 0.14335779  0.44759526  0.43805705]
 [ 0.13341822  0.44872918  0.18029881]
 [ 0.40169708  0.43772409  0.24545021]]
[[2 1 0]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [2 1 0]
 [1 2 0]
 [0 2 1]
 [0 2 1]
 [0 2 1]
 [2 0 1]]


[0.62805836653172853,
 0.36123024984225416,
 0.50178720544048483,
 0.57241649152196983,
 0.28669129098339829,
 0.49316911825501453,
 0.59575332948480753,
 0.35664221401273943,
 0.63341822012740401,
 0.25454979015173618]

In [7]:
# 4. Picture Manipulation: Framing a Face

In [24]:
from scipy import misc
face = misc.face(gray=True)

In [25]:
# use PyLab's imshow fxn to display the image as-is
import pylab as plb
plb.imshow(face)

In [26]:
plb.show() # Displays in false colors

In [27]:
# Fix the false colors show above by specifying a colormap
plb.imshow(face, cmap=plb.cm.gray)

In [28]:
plb.show()

In [29]:
# Narrower centering: crop the image by 100px on all sides
crop_face = face[100:-100, 100:-100]
plb.imshow(crop_face, cmap=plb.cm.gray)

In [30]:
plb.show()

In [31]:
# Now, frame the face in a circle, with the rest of the image area colored black
# a. create a mask for the pixels that should be black
#    The face is around (660, 300), so we define the mask to be outside the circle described by a circle centered at
#    (y - 300)**2 + (x - 660)**2 (the end of that line) and define the radius to be 230**2
sy, sx = face.shape
y, x = np.ogrid[0:sy, 0:sx]
print((x.shape, y.shape))
centerx, centery = (660, 300) # where the supposed center of the face is located (will be the center of the circle)
mask = ((y - centery)**2 + (x - centerx)**2) > 230**2
face[mask] = 0 # convert the coordinates in `mask` to 0, which makes them black
plb.imshow(face)

((1, 1024), (768, 1))


In [32]:
plb.show()

In [ ]:
# The next instruction is to make the circle a 3D ellipsoid, but that makes no sense on a 2D image, so I'm assuming the
# author meant `ellipse`.

face = misc.face(gray=True)
# To create an elipse, you need 2 foci equidistant from the center where the circumference of the elipse is the set of
# points drawn by keeping the sum of the distances from both foci constant.
# The length of each radii is given by (x / a)**2 and (y / b)**2 where their sum == 1.
sy, sx = face.shape
y, x = np.ogrid[0:sy, 0:sx]
centerx, centery = (660, 350)
mask = (((y - centery) / 140)**2 + ((x - centerx) / 200)**2) > 1
face[mask] = 0
plb.imshow(face)

In [ ]:
plb.show()