In [1]:
import numpy as np

In [2]:
# 1.
# Form the following 2D array using NumPy fxns.
# [[1,  6, 11],
#  [2,  7, 12],
#  [3,  8, 13],
#  [4,  9, 14],
#  [5, 10, 15]]

mat = np.arange(1,16).reshape((3,5)).T
mat

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [3]:
# Also, create a second array which contains only the 2nd and 4th rows.
new_mat = mat[[1,3]]
new_mat

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [4]:
# 2.
# Divide each column of the array np.arange(25).reshape(5,5) elementwise with the array [1., 5, 15, 20]
mat = np.arange(25).reshape(5,5)
arr = np.array([1., 5, 10, 15, 20])
mat / arr[:, np.newaxis]
# New access turns the arr which is a row into a column - autobroadcasting handles propogating the row across all the
# columns of mat.

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.2       ,  1.4       ,  1.6       ,  1.8       ],
       [ 1.        ,  1.1       ,  1.2       ,  1.3       ,  1.4       ],
       [ 1.        ,  1.06666667,  1.13333333,  1.2       ,  1.26666667],
       [ 1.        ,  1.05      ,  1.1       ,  1.15      ,  1.2       ]])

In [6]:
# 3.
# Generate a 10 x 3 matrix of random numbers in the Set [0,1].  For each row, choose the number closest to 0.5.
#   Additional instructions: use `abs` and `argsort` to pick the column j of the closest number to 0.5 for each row
#                            Use fancy indexing to extract the numbers

In [61]:
mat = np.random.sample((10,3))
print(mat)
distances_from_half = np.abs(mat - 0.5)
print(distances_from_half)
sort_values = np.argsort(distances_from_half)
print(sort_values)
closest_indices = sort_values
closest_index_pairs = [ (i, sort_values[i][0]) for i in np.arange(0, sort_values.shape[0]) ]
closest_numbers = [ mat[i[0], i[1]] for i in closest_index_pairs]
closest_numbers

[[ 0.00203033  0.9975632   0.17093592]
 [ 0.85876879  0.78079256  0.47921052]
 [ 0.36717863  0.21431179  0.710931  ]
 [ 0.43928614  0.54019885  0.63370977]
 [ 0.05878514  0.15148066  0.59947661]
 [ 0.72956135  0.69455862  0.64101071]
 [ 0.26065548  0.58213876  0.6469138 ]
 [ 0.30497904  0.23653318  0.6588665 ]
 [ 0.835493    0.05978209  0.1551167 ]
 [ 0.08399699  0.75835136  0.55555325]]
[[ 0.49796967  0.4975632   0.32906408]
 [ 0.35876879  0.28079256  0.02078948]
 [ 0.13282137  0.28568821  0.210931  ]
 [ 0.06071386  0.04019885  0.13370977]
 [ 0.44121486  0.34851934  0.09947661]
 [ 0.22956135  0.19455862  0.14101071]
 [ 0.23934452  0.08213876  0.1469138 ]
 [ 0.19502096  0.26346682  0.1588665 ]
 [ 0.335493    0.44021791  0.3448833 ]
 [ 0.41600301  0.25835136  0.05555325]]
[[2 1 0]
 [2 1 0]
 [0 2 1]
 [1 0 2]
 [2 1 0]
 [2 1 0]
 [1 2 0]
 [2 0 1]
 [0 2 1]
 [2 1 0]]


[0.17093592440575445,
 0.47921051637712919,
 0.36717862794929412,
 0.54019884614268099,
 0.59947661318841139,
 0.64101070708847963,
 0.58213875654710068,
 0.65886649880126891,
 0.83549299512664854,
 0.55555325126601385]