In [1]:
import numpy as np

In [2]:
# 1.
# Form the following 2D array using NumPy fxns.
# [[1,  6, 11],
#  [2,  7, 12],
#  [3,  8, 13],
#  [4,  9, 14],
#  [5, 10, 15]]

mat = np.arange(1,16).reshape((3,5)).T
mat

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [3]:
# Also, create a second array which contains only the 2nd and 4th rows.
new_mat = mat[[1,3]]
new_mat

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [4]:
# 2.
# Divide each column of the array np.arange(25).reshape(5,5) elementwise with the array [1., 5, 15, 20]
mat = np.arange(25).reshape(5,5)
arr = np.array([1., 5, 10, 15, 20])
mat / arr[:, np.newaxis]
# New access turns the arr which is a row into a column - autobroadcasting handles propogating the row across all the
# columns of mat.

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.2       ,  1.4       ,  1.6       ,  1.8       ],
       [ 1.        ,  1.1       ,  1.2       ,  1.3       ,  1.4       ],
       [ 1.        ,  1.06666667,  1.13333333,  1.2       ,  1.26666667],
       [ 1.        ,  1.05      ,  1.1       ,  1.15      ,  1.2       ]])

In [6]:
# 3.
# Generate a 10 x 3 matrix of random numbers in the Set [0,1].  For each row, choose the number closest to 0.5.
#   Additional instructions: use `abs` and `argsort` to pick the column j of the closest number to 0.5 for each row
#                            Use fancy indexing to extract the numbers

In [47]:
mat = np.random.sample((10,3))
print(mat)
distances_from_half = np.abs(mat - 0.5)
print(distances_from_half)
sort_values = distances_from_half.argsort()
print(sort_values)
closest_indices = np.where(sort_values == 0)
closest_index_pairs = zip(closest_indices[0], closest_indices[1])
closest_numbers = [ mat[i[0], i[1]] for i in closest_index_pairs]
closest_numbers

[[ 0.71734029  0.03597785  0.12945157]
 [ 0.85574884  0.43705871  0.58043617]
 [ 0.76739054  0.61570864  0.62498967]
 [ 0.51686953  0.71710744  0.57047811]
 [ 0.84399185  0.81771106  0.89670084]
 [ 0.20211826  0.41451459  0.65329654]
 [ 0.8458387   0.67235007  0.08232822]
 [ 0.72678461  0.7072841   0.14965203]
 [ 0.75954905  0.64691586  0.96549302]
 [ 0.27130298  0.38191204  0.55123423]]
[[ 0.21734029  0.46402215  0.37054843]
 [ 0.35574884  0.06294129  0.08043617]
 [ 0.26739054  0.11570864  0.12498967]
 [ 0.01686953  0.21710744  0.07047811]
 [ 0.34399185  0.31771106  0.39670084]
 [ 0.29788174  0.08548541  0.15329654]
 [ 0.3458387   0.17235007  0.41767178]
 [ 0.22678461  0.2072841   0.35034797]
 [ 0.25954905  0.14691586  0.46549302]
 [ 0.22869702  0.11808796  0.05123423]]
[[0 2 1]
 [1 2 0]
 [1 2 0]
 [0 2 1]
 [1 0 2]
 [1 2 0]
 [1 0 2]
 [1 0 2]
 [1 0 2]
 [2 1 0]]


[0.71734029087506546,
 0.58043617273179304,
 0.62498966653410271,
 0.51686953106946998,
 0.81771106101773938,
 0.65329653683550826,
 0.67235007332267938,
 0.70728410065717418,
 0.6469158595466219,
 0.55123423006270589]

In [48]:
np.argsort?