In [3]:
import numpy as np

In [4]:

# Polynomials


In [5]:
# NumPy also contains polynomials in different bases
# The below represents 3x^2 + 2x - 1
p = np.poly1d([3,2,-1])
p(0)

-1

In [6]:
p.roots

array([-1.        ,  0.33333333])

In [8]:
p.order

2

In [13]:
3*(-1**2) + 2*(-1) - 1

-6

In [17]:
from matplotlib import pyplot as plt

In [20]:
x = np.linspace(0,1,20)
print(x)
y = np.cos(x) + 0.3*np.random.rand(20)
print(y)
p = np.poly1d(np.polyfit(x, y, 3))

t = np.linspace(0,1,200)
plt.plot(x,y,'o',t, p(t), '-')
plt.show()

[ 0.          0.05263158  0.10526316  0.15789474  0.21052632  0.26315789
  0.31578947  0.36842105  0.42105263  0.47368421  0.52631579  0.57894737
  0.63157895  0.68421053  0.73684211  0.78947368  0.84210526  0.89473684
  0.94736842  1.        ]
[ 1.14786635  1.2290052   1.19939692  1.14839643  1.01256922  1.14384042
  1.19749     1.11865114  0.97043437  0.94903709  0.97162826  1.08863578
  0.96979643  0.97224939  0.94477379  0.73127738  0.79686525  0.67084077
  0.86547399  0.65941789]


In [21]:
np.polyfit?

In [22]:
# More Polynomials

# NumPy has a more sophisticated polynomial interface.  It supports the Chevychev basis.
# 3x^2 + 2x - 1 again
p = np.polynomial.Polynomial([-1,2,3]) # Coefficients in ascending order of degree rather than descending as above.
p(0)

-1.0

In [23]:
p.roots()

array([-1.        ,  0.33333333])

In [24]:
p.degree() # In general, polynomials don't always expose order

2

In [30]:
# Example of using polynomials in Chevychev basis, for polynomials in range [-1, 1]
x = np.linspace(-1,1,2000)
y = np.cos(x) + 0.3*np.random.rand(2000)
p = np.polynomial.Chebyshev.fit(x,y,90)

t = np.linspace(-1,1,200)
plt.plot(x,y,'r.')

In [31]:
plt.plot(t, p(t), 'k-', lw=3)

In [32]:
plt.show()

In [33]:
### Lookup chebychev basis and review polynomial roots.

In [34]:

# Loading Data Files


In [36]:
# Text Filse
data = np.loadtxt('data/populations.txt')
data

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [37]:
np.savetxt('pop2.txt', data)
data2 = np.loadtxt('pop2.txt')
data2

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [39]:
np.genfromtxt?

In [41]:
# Refresher filesystem commands
%pwd

'/Users/dt205208/Development/scipy-lectures/Ch1/SciPy_NumPy'

In [42]:
%cd .

/Users/dt205208/Development/scipy-lectures/Ch1/SciPy_NumPy


In [43]:
%ls

Ch_1_3_1-TheNumPyArrayObj.ipynb
Ch_1_3_2_Numerical_Operations_on_Arrays.ipynb
Ch_1_3_3_More_Elaborate_Arrays.ipynb
Ch_1_3_4_Advanced_Operations.ipynb
data/
pop2.txt
prime_sieve.py


In [44]:
# Images
# using matplotlib
img = plt.imread('data/spock_eyebrow_large.png')
img.shape, img.dtype

((621, 597, 4), dtype('float32'))

In [51]:
plt.imshow(img)
plt.savefig('plot.png')
plt.imshow(plt.imread('plot.png'))

In [52]:
plt.show() # The saved plot read back in full RGB

In [53]:
plt.imsave('red_spock', img[:,:,0], cmap=plt.cm.gray)

In [54]:
plt.imshow(plt.imread('red_spock.png'))

In [55]:
plt.show() # The grayscale image

In [57]:
# Other libraries
from scipy.misc import imsave
imsave('tiny_spock.png', img[::6,::6])

In [58]:
plt.imshow(plt.imread('tiny_spock.png'), interpolation='nearest')

In [59]:
plt.show()

In [61]:
# NumPy's Own Format

# NumPy has its own binary format which is not portable, but it IS efficient at I/O WITHIN NumPy
data = np.ones((3,3))
np.save('pop.npy', data)

In [62]:
data3 = np.load('pop.npy')
data3

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])