In [1]:
import numpy as np

In [2]:
# 1.
# Form the following 2D array using NumPy fxns.
# [[1,  6, 11],
#  [2,  7, 12],
#  [3,  8, 13],
#  [4,  9, 14],
#  [5, 10, 15]]

mat = np.arange(1,16).reshape((3,5)).T
mat

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [3]:
# Also, create a second array which contains only the 2nd and 4th rows.
new_mat = mat[[1,3]]
new_mat

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [4]:
# 2.
# Divide each column of the array np.arange(25).reshape(5,5) elementwise with the array [1., 5, 15, 20]
mat = np.arange(25).reshape(5,5)
arr = np.array([1., 5, 10, 15, 20])
mat / arr[:, np.newaxis]
# New access turns the arr which is a row into a column - autobroadcasting handles propogating the row across all the
# columns of mat.

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.2       ,  1.4       ,  1.6       ,  1.8       ],
       [ 1.        ,  1.1       ,  1.2       ,  1.3       ,  1.4       ],
       [ 1.        ,  1.06666667,  1.13333333,  1.2       ,  1.26666667],
       [ 1.        ,  1.05      ,  1.1       ,  1.15      ,  1.2       ]])

In [5]:
# 3.
# Generate a 10 x 3 matrix of random numbers in the Set [0,1].  For each row, choose the number closest to 0.5.
#   Additional instructions: use `abs` and `argsort` to pick the column j of the closest number to 0.5 for each row
#                            Use fancy indexing to extract the numbers

In [6]:
mat = np.random.sample((10,3))
print(mat)
distances_from_half = np.abs(mat - 0.5)
print(distances_from_half)
sort_values = np.argsort(distances_from_half)
print(sort_values)
closest_indices = sort_values
closest_index_pairs = [ (i, sort_values[i, 0]) for i in np.arange(0, sort_values.shape[0]) ]
closest_numbers = [ mat[i[0], i[1]] for i in closest_index_pairs ]
closest_numbers

[[ 0.37982368  0.15979191  0.6666393 ]
 [ 0.49172608  0.22427759  0.63270175]
 [ 0.54337912  0.30239876  0.37588553]
 [ 0.56588004  0.21052147  0.67148153]
 [ 0.85813839  0.44100763  0.2333871 ]
 [ 0.15869359  0.57047259  0.81876425]
 [ 0.27705154  0.83060062  0.62361692]
 [ 0.43456765  0.57272231  0.00844132]
 [ 0.10833938  0.19480763  0.25772459]
 [ 0.02098086  0.08744714  0.66409939]]
[[ 0.12017632  0.34020809  0.1666393 ]
 [ 0.00827392  0.27572241  0.13270175]
 [ 0.04337912  0.19760124  0.12411447]
 [ 0.06588004  0.28947853  0.17148153]
 [ 0.35813839  0.05899237  0.2666129 ]
 [ 0.34130641  0.07047259  0.31876425]
 [ 0.22294846  0.33060062  0.12361692]
 [ 0.06543235  0.07272231  0.49155868]
 [ 0.39166062  0.30519237  0.24227541]
 [ 0.47901914  0.41255286  0.16409939]]
[[0 2 1]
 [0 2 1]
 [0 2 1]
 [0 2 1]
 [1 2 0]
 [1 2 0]
 [2 0 1]
 [0 1 2]
 [2 1 0]
 [2 1 0]]


[0.37982367767966707,
 0.49172608293976838,
 0.54337912299281499,
 0.56588004094619082,
 0.44100762920831338,
 0.57047259098459013,
 0.6236169203154206,
 0.43456764902368072,
 0.25772458914919227,
 0.66409938773647581]

In [7]:
# 4. Picture Manipulation: Framing a Face

In [8]:
from scipy import misc
face = misc.face(gray=True)

In [9]:
# use PyLab's imshow fxn to display the image as-is
import pylab as plb
plb.imshow(face)

In [10]:
plb.show() # Displays in false colors

In [11]:
# Fix the false colors show above by specifying a colormap
plb.imshow(face, cmap=plb.cm.gray)

In [12]:
plb.show()

In [13]:
# Narrower centering: crop the image by 100px on all sides
crop_face = face[100:-100, 100:-100]
plb.imshow(crop_face, cmap=plb.cm.gray)

In [14]:
plb.show()

In [15]:
# Now, frame the face in a circle, with the rest of the image area colored black
# a. create a mask for the pixels that should be black
#    The face is around (660, 300), so we define the mask to be outside the circle described by a circle centered at
#    (y - 300)**2 + (x - 660)**2 (the end of that line) and define the radius to be 230**2
sy, sx = face.shape
y, x = np.ogrid[0:sy, 0:sx]
print((x.shape, y.shape))
centerx, centery = (660, 300) # where the supposed center of the face is located (will be the center of the circle)
mask = ((y - centery)**2 + (x - centerx)**2) > 230**2
face[mask] = 0 # convert the coordinates in `mask` to 0, which makes them black
plb.imshow(face)

((1, 1024), (768, 1))


In [16]:
plb.show()

In [17]:
# The next instruction is to make the circle a 3D ellipsoid, but that makes no sense on a 2D image, so I'm assuming the
# author meant `ellipse`.

face = misc.face(gray=True)
# To create an elipse, you need 2 foci equidistant from the center where the circumference of the elipse is the set of
# points drawn by keeping the sum of the distances from both foci constant.
# The length of each radii is given by (x / a)**2 and (y / b)**2 where their sum == 1.
sy, sx = face.shape
y, x = np.ogrid[0:sy, 0:sx]
centerx, centery = (660, 350)
mask = (((y - centery) / 140)**2 + ((x - centerx) / 200)**2) > 1
face[mask] = 0
plb.imshow(face)

In [18]:
plb.show()

In [19]:
# Data statistics

In [20]:
data = np.loadtxt('data/populations.txt')
data

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [21]:
year, hares, lynxes, carrots = data.T

In [22]:
import matplotlib.pyplot as plt

In [23]:
plt.axes([0.2, 0.1, 0.5, 0.8])

In [24]:
plt.plot(year, hares, year, lynxes, year, carrots)

In [25]:
plt.legend(('Hare', 'Lynx', 'Carrot'), loc=(1.05, 0.5))

In [26]:
plt.show()

In [27]:
# Exercises

In [28]:
populations = data[:,1:]
populations

array([[ 30000.,   4000.,  48300.],
       [ 47200.,   6100.,  48200.],
       [ 70200.,   9800.,  41500.],
       [ 77400.,  35200.,  38200.],
       [ 36300.,  59400.,  40600.],
       [ 20600.,  41700.,  39800.],
       [ 18100.,  19000.,  38600.],
       [ 21400.,  13000.,  42300.],
       [ 22000.,   8300.,  44500.],
       [ 25400.,   9100.,  42100.],
       [ 27100.,   7400.,  46000.],
       [ 40300.,   8000.,  46800.],
       [ 57000.,  12300.,  43800.],
       [ 76600.,  19500.,  40900.],
       [ 52300.,  45700.,  39400.],
       [ 19500.,  51100.,  39000.],
       [ 11200.,  29700.,  36700.],
       [  7600.,  15800.,  41800.],
       [ 14600.,   9700.,  43300.],
       [ 16200.,  10100.,  41300.],
       [ 24700.,   8600.,  47300.]])

In [29]:
populations.mean(axis=0)

array([ 34080.95238095,  20166.66666667,  42400.        ])

In [30]:
populations.std(axis=0)

array([ 20897.90645809,  16254.59153691,   3322.50622558])

In [31]:
largest_pop_year_index = np.argmax(populations, axis=0)
year[largest_pop_year_index]

array([ 1903.,  1904.,  1900.])

In [32]:
max_pop_species_by_year = np.argmax(populations, axis=1)
max_pop_species_by_year

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [33]:
np.array(['Hare', 'Lynx', 'Carrot'])[max_pop_species_by_year]

array(['Carrot', 'Carrot', 'Hare', 'Hare', 'Lynx', 'Lynx', 'Carrot',
       'Carrot', 'Carrot', 'Carrot', 'Carrot', 'Carrot', 'Hare', 'Hare',
       'Hare', 'Lynx', 'Carrot', 'Carrot', 'Carrot', 'Carrot', 'Carrot'], 
      dtype='<U6')

In [34]:
list(zip(np.array(['Hare', 'Lynx', 'Carrot'])[max_pop_species_by_year], year))

[('Carrot', 1900.0),
 ('Carrot', 1901.0),
 ('Hare', 1902.0),
 ('Hare', 1903.0),
 ('Lynx', 1904.0),
 ('Lynx', 1905.0),
 ('Carrot', 1906.0),
 ('Carrot', 1907.0),
 ('Carrot', 1908.0),
 ('Carrot', 1909.0),
 ('Carrot', 1910.0),
 ('Carrot', 1911.0),
 ('Hare', 1912.0),
 ('Hare', 1913.0),
 ('Hare', 1914.0),
 ('Lynx', 1915.0),
 ('Carrot', 1916.0),
 ('Carrot', 1917.0),
 ('Carrot', 1918.0),
 ('Carrot', 1919.0),
 ('Carrot', 1920.0)]

In [35]:
above50000 = np.any(populations > 50000, axis=1)
year[above50000]

array([ 1902.,  1903.,  1904.,  1912.,  1913.,  1914.,  1915.])

In [36]:
top_2_yrs_lowest_pop_each_species_idx = np.argsort(populations, axis=0)[:2]
top_2_yrs_lowest_pop_each_species_idx

array([[17,  0, 16],
       [16,  1,  3]])

In [37]:
year[top_2_yrs_lowest_pop_each_species_idx]

array([[ 1917.,  1900.,  1916.],
       [ 1916.,  1901.,  1903.]])

In [38]:
hare_grad = np.gradient(hares, 1.0)
hare_grad

array([ 17200.,  20100.,  15100., -16950., -28400.,  -9100.,    400.,
         1950.,   2000.,   2550.,   7450.,  14950.,  18150.,  -2350.,
       -28550., -20550.,  -5950.,   1700.,   4300.,   5050.,   8500.])

In [39]:
hares_vs_lynx_correlation = np.corrcoef(hare_grad, lynxes)[0,1]
hares_vs_lynx_correlation

-0.91792484803153407

In [40]:
plt.plot(year, hare_grad, year, -lynxes)
plt.show()

In [41]:
# Crude Integral Approximations